#![allow(clippy::ptr_arg)]
//! Build script for guest circuits (chunk, batch, bundle).
//!
//! This script builds OpenVM guest programs and generates associated assets:
//!
//! ## App Assets Generation:
//! 1. Builds guest programs (ELF) for specified projects
//! 2. Transpiles ELF files to VM executables (.vmexe)
//! 3. Generates executable and VM commitments
//! 4. Creates verification keys and supporting files
//!
//! ## OpenVM Assets Generation:
//! 1. Generates EVM verifier contract (Solidity) and bytecode
//!
//! ## Usage:
//! ```bash
//! cargo run --bin build-guest [OPTIONS]
//! ```
//!
//! ## Options:
//! - `--mode <MODE>`: Generation mode (auto|force)
//!   - `auto`: Skip generation if output files already exist (default, faster for development)
//!   - `force`: Always regenerate all files (use for clean builds or CI)
//!
//! ## Environment Variables:
//! - `BUILD_PROJECT`: Comma-separated list of projects to build (e.g. "chunk,batch").
//!   Defaults to "chunk,batch,bundle".
//!
//! ## Output:
//! - App assets: `releases/dev/{project_name}/`
//! - OpenVM assets: `releases/dev/verifier/`
//! - Commitment files: Written to respective circuit crate directories

use clap::{Parser, ValueEnum};
use dotenvy::dotenv;
use eyre::Result;
use openvm_build::GuestOptions;
use openvm_instructions::exe::VmExe;
use openvm_circuit::arch::instructions::DEFERRAL_AS;
use openvm_recursion_circuit::batch_constraint::commit_child_vk;
use openvm_stark_backend::StarkEngine;
use openvm_sdk::{
    F, Sdk,
    config::{AggregationConfig, AggregationSystemParams, AggregationTreeConfig, AppConfig},
    fs::write_object_to_file,
    prover::MultiDeferralCircuitProver,
};
use openvm_sdk_config::{SdkVmConfig, deferral::SupportedDeferral};
use openvm_continuations::CommitBytes;
use openvm_stark_sdk::{
    config::{app_params_with_100_bits_security, hook_params_with_100_bits_security, internal_params_with_100_bits_security, leaf_params_with_100_bits_security, MAX_APP_LOG_STACKED_HEIGHT},
    openvm_stark_backend::p3_field::PrimeField32,
};
use openvm_verify_stark_circuit::prover::{
    DeferredVerifyCpuCircuitProver as VerifyCircuitProver,
    DeferredVerifyCpuProver as VerifyProver,
};
use openvm_stark_sdk::config::baby_bear_poseidon2::BabyBearPoseidon2CpuEngine as DeferralEngine;
use std::{
    env, fs,
    path::{Path, PathBuf},
    sync::Arc,
    time::Instant,
};

mod verifier;

const DIGEST_SIZE: usize = 8;

/// Default aggregation parameters used across chunk, batch, and bundle circuits.
fn default_agg_params() -> AggregationSystemParams {
    AggregationSystemParams {
        leaf: leaf_params_with_100_bits_security(),
        internal: internal_params_with_100_bits_security(),
    }
}

#[derive(Debug, Clone, ValueEnum)]
enum OutputMode {
    /// Skip generation when output file already exists (default)
    Auto,
    /// Always overwrite existing files
    Force,
}

#[derive(Parser)]
#[command(name = "build-guest")]
#[command(about = "Build script for guest circuits (chunk, batch, bundle)")]
struct Cli {
    /// Generation mode for OpenVM assets:
    /// - auto: Skip generation if output files already exist (faster for development)
    /// - force: Always regenerate all files (use for clean builds or CI)
    #[arg(long, value_enum, default_value_t = OutputMode::Auto)]
    mode: OutputMode,

    /// Output directory name under releases/ (default: "dev")
    #[arg(long, default_value = "dev")]
    output: String,
}

const LOG_PREFIX: &str = "[build-guest]";

/// File descriptor for app openvm config.
const FD_APP_CONFIG: &str = "openvm.toml";

/// Writes a commitment array to a Rust source file.
fn write_commitment(output_path: &PathBuf, commitment: [u32; DIGEST_SIZE]) -> Result<()> {
    let content = format!(
        "#![cfg_attr(rustfmt, rustfmt_skip)]\n//! Generated by crates/build-guest. DO NOT EDIT!\n\npub const COMMIT: [u32; {DIGEST_SIZE}] = {commitment:?};\n"
    );
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output_path, content)?;

    println!("{LOG_PREFIX} Wrote commitment to {}", output_path.display());

    Ok(())
}

/// Writes a commitment array as canonical-form hex.
///
/// The EVM verifier constructor (`ZkEvmVerifierPostFeynman`) expects digests in
/// canonical form (big-endian). The proof instances also contain canonical
/// digests, so this file can be used directly without Montgomery conversion.
fn write_commitment_as_evm_hex(
    output_path: &PathBuf,
    commitment: [u32; DIGEST_SIZE],
) -> Result<()> {
    let commit_bytes = CommitBytes::from(commitment);
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    fs::write(output_path, hex::encode(commit_bytes.as_slice()))?;
    println!("{LOG_PREFIX} Wrote commitment to {}", output_path.display());
    Ok(())
}

/// Build a MultiDeferralCircuitProver from a child SDK and the parent app config
/// (CPU-only; build-guest does not use cuda).
fn make_deferral_prover(
    child_sdk: &Sdk,
    parent_app_config: &AppConfig<SdkVmConfig>,
    agg_params: &AggregationSystemParams,
) -> MultiDeferralCircuitProver {
    let child_agg_vk = child_sdk.agg_vk().clone();
    let engine = <DeferralEngine as StarkEngine>::new(child_agg_vk.inner.params.clone());
    let internal_recursive_cached_commit: CommitBytes =
        commit_child_vk(&engine, &child_agg_vk, true)
            .commitment
            .into();

    // The verify-stark deferral circuit runs as part of the *parent* VM, so its
    // memory layout and public-value count must match the parent's config.
    let system_config = parent_app_config.app_vm_config.as_ref().clone();
    let memory_dimensions = system_config.memory_config.memory_dimensions();
    let num_user_pvs = system_config.num_public_values;

    let def_circuit_params = internal_params_with_100_bits_security();
    let child_def_hook_commit: Option<CommitBytes> = child_sdk.def_hook_commit().map(|c| c.into());
    let deferred_verify_prover = VerifyProver::new::<DeferralEngine>(
        child_agg_vk,
        internal_recursive_cached_commit,
        def_circuit_params,
        memory_dimensions,
        num_user_pvs,
        child_def_hook_commit,
        0,
    );
    let verify_stark_prover = VerifyCircuitProver::new(deferred_verify_prover);
    let hook_params = hook_params_with_100_bits_security();
    let agg_config = AggregationConfig {
        params: agg_params.clone(),
    };
    MultiDeferralCircuitProver::new(verify_stark_prover, agg_config, hook_params)
}

/// Builds guest programs, transpiles them, and generates executable commitments.
fn generate_app_assets(workspace_dir: &Path, release_output_dir: &PathBuf) -> Result<()> {
    println!("{LOG_PREFIX} === Generating App Assets ===");

    // Determine which projects to build
    let projects_to_build_str = env::var("BUILD_PROJECT");
    let projects_to_build = projects_to_build_str
        .as_ref()
        .map(|s| s.split(',').filter(|p| !p.is_empty()).collect::<Vec<_>>())
        .unwrap_or_else(|_| vec!["chunk", "batch", "bundle"]); // Default projects

    println!("{LOG_PREFIX} Projects to build: {:?}", projects_to_build);

    let _app_params = app_params_with_100_bits_security(21);
    let agg_params = default_agg_params();

    let mut vk_dump: serde_json::Value = serde_json::from_str("{}")?;
    let mut prev_sdk: Option<Sdk> = None;

    for project_name in projects_to_build {
        let project_path = workspace_dir
            .join("crates")
            .join("circuits")
            .join(format!("{project_name}-circuit"));

        println!("{LOG_PREFIX} Processing project: {project_name}");

        let start_time = Instant::now();
        println!("{LOG_PREFIX} Starting build...");

        let project_dir = project_path.to_str().expect("Invalid path");
        // First read the app config specified in the project's root directory.
        let path_app_config = Path::new(project_dir).join(FD_APP_CONFIG);
        let mut app_config: AppConfig<SdkVmConfig> =
            toml::from_str(&fs::read_to_string(&path_app_config)?)?;
        println!(
            "{project_dir} app config: {}",
            toml::to_string_pretty(&app_config)?
        );

        // Reserve deferral address space for all projects; SdkVmConfig::optimize() will zero it
        // for circuits that do not enable deferral.
        app_config.app_vm_config.system.config.memory_config.addr_spaces
            [DEFERRAL_AS as usize]
            .num_cells = 1 << 25;

        // Enable deferral for aggregation circuits using the previous SDK
        let deferral_prover: Option<MultiDeferralCircuitProver> =
            if (project_name == "batch" || project_name == "bundle") && prev_sdk.is_some()
            {
                let child_sdk = prev_sdk.as_ref().unwrap();
                let deferral_prover = make_deferral_prover(child_sdk, &app_config, &agg_params);
                let deferral_config = deferral_prover
                    .make_config(vec![SupportedDeferral::VerifyStark]);
                app_config.app_vm_config.deferral = Some(deferral_config);
                Some(deferral_prover)
            } else {
                None
            };

        // Write config (possibly modified with deferral) to release output dir
        let output_path = release_output_dir.join(project_name).join(FD_APP_CONFIG);
        if let Some(parent) = output_path.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&output_path, toml::to_string_pretty(&app_config)?)?;
        println!("{LOG_PREFIX} Wrote config to {}", output_path.display());

        // Build SDK with the project-specific app config
        let mut sdk_builder = Sdk::builder()
            .app_config(app_config.clone())
            .agg_params(agg_params.clone());
        if let Some(dp) = deferral_prover {
            sdk_builder = sdk_builder.multi_deferral_circuit_prover(dp);
        }
        let sdk = sdk_builder.build()?;

        // 1. Build ELF

        // Store current directory and change to project directory
        let original_dir = env::current_dir()?;
        env::set_current_dir(&project_path)?;
        println!(
            "{LOG_PREFIX} Changed working directory to: {}",
            project_path.display()
        );
        let guest_opts = GuestOptions {
            features: if project_name == "chunk" && cfg!(feature = "scroll") {
                vec!["scroll".to_string()]
            } else {
                vec![]
            },
            ..Default::default()
        };
        let guest_opts = guest_opts.with_profile("maxperf".to_string());
        let elf = sdk
            .build(guest_opts, project_dir, &Default::default(), None)
            .inspect_err(|_err| {
                println!("{LOG_PREFIX} Building failed in {}", project_dir);
            })?;
        println!("{LOG_PREFIX} Built ELF");

        // Revert to original directory
        env::set_current_dir(&original_dir)?;
        println!(
            "{LOG_PREFIX} Reverted working directory to: {}",
            original_dir.display()
        );

        // Create the assets dir if not already present.
        let path_assets = Path::new(release_output_dir).join(project_name);
        fs::create_dir_all(&path_assets)?;
        let elf_src = workspace_dir
            .join("target")
            .join("riscv32im-risc0-zkvm-elf")
            .join("maxperf")
            .join(format!("scroll-zkvm-{project_name}-circuit"));
        let path_app_elf: PathBuf = path_assets.join("app.elf");
        fs::copy(&elf_src, &path_app_elf)?;
        println!("{LOG_PREFIX} elf written to {path_app_elf:?}");

        // 2. Transpile ELF to VM Executable
        let app_exe: VmExe<F> = (*sdk.convert_to_exe(elf)?).clone();

        // Write exe to disc.
        let path_app_exe: PathBuf = path_assets.join("app.vmexe");
        write_object_to_file(&path_app_exe, app_exe.clone())?;
        println!("{LOG_PREFIX} exe written to {path_app_exe:?}");

        // 3. Compute and Write Executable Commitment
        let prover = sdk.prover(Arc::new(app_exe.clone()))?;
        let exe_digest = prover.app_prover.app_exe_commit();
        let vm_digest = prover.app_vm_commit();
        let exe_commit_u32: [u32; DIGEST_SIZE] = std::array::from_fn(|i| exe_digest[i].as_canonical_u32());
        let vm_commit_u32: [u32; DIGEST_SIZE] = std::array::from_fn(|i| vm_digest[i].as_canonical_u32());

        write_commitment(
            &Path::new(project_dir).join(format!("{project_name}_exe_commit.rs")),
            exe_commit_u32,
        )?;
        write_commitment(
            &Path::new(project_dir).join(format!("{project_name}_vm_commit.rs")),
            vm_commit_u32,
        )?;

        // Special handling for bundle project
        if project_name == "bundle" {
            // Primary files: canonical form, usable directly by EVM verifier constructors.
            let output_path = release_output_dir.join(project_name).join("digest_1.hex");
            write_commitment_as_evm_hex(&output_path, exe_commit_u32)?;
            let output_path = release_output_dir.join(project_name).join("digest_2.hex");
            write_commitment_as_evm_hex(&output_path, vm_commit_u32)?;
        }

        use scroll_zkvm_types::{types_agg::ProgramCommitment, utils::serialize_vk};
        let app_vk = serialize_vk::serialize(&ProgramCommitment {
            exe: exe_commit_u32,
            vm: vm_commit_u32,
        });

        let app_vk = hex::encode(&app_vk);
        println!("{project_name}: {app_vk}");

        vk_dump[format!("{project_name}_vk")] = serde_json::Value::String(app_vk);

        println!(
            "{LOG_PREFIX} Finished build for config in {:?}",
            start_time.elapsed()
        );

        prev_sdk = Some(sdk);
    }

    let output_path = release_output_dir.join("verifier").join("openVmVk.json");
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)?;
    }
    let f = fs::File::create(output_path)?;
    serde_json::to_writer(f, &vk_dump)?;
    println!(
        "{LOG_PREFIX} openVmVk.json: {}",
        serde_json::to_string_pretty(&vk_dump)?
    );
    println!("{LOG_PREFIX} VK data written to openVmVk.json");
    Ok(())
}

/// Root verifier assembly is no longer needed in v2 (deferred compute model).
fn generate_root_verifier(_workspace_dir: &Path, _force_overwrite: bool) -> Result<()> {
    println!("{LOG_PREFIX} === Root Verifier Assembly ===");
    println!("{LOG_PREFIX} Skipping: root verifier ASM is deprecated in OpenVM v2");
    Ok(())
}

/// Default aggregation-tree shape used by the host prover and the EVM verifier.
///
/// Must stay in sync with [`Prover::get_sdk`](crates/prover/src/prover/mod.rs).
const DEFAULT_AGG_TREE_CONFIG: AggregationTreeConfig = AggregationTreeConfig {
    num_children_internal: 3,
    num_children_leaf: 4,
};

/// Generate the EVM verifier Solidity contract and its deployment bytecode.
///
/// # Modes
///
/// ## `RECOMPUTE_MODE=yes` (recommended for releases)
/// Re-generates the verifier from scratch using the local OpenVM SDK.
/// This requires:
/// 1. Building a **batch SDK** to obtain the deferral prover (matches host prover config).
/// 2. Loading the **bundle app config** so the verifier hardcodes the same aggregation-tree
///    shape and deferral settings as the bundle circuit.
///
/// ## Download mode (default)
/// Downloads a pre-built Solidity verifier from `openvm-solidity-sdk`.
/// No bytecode is produced; only the `.sol` file is fetched.
fn generate_evm_verifier(
    _workspace_dir: &Path,
    release_output_dir: &PathBuf,
    verifier_output_dir: &PathBuf,
    recompute_mode: bool,
    force_overwrite: bool,
) -> Result<()> {
    println!("{LOG_PREFIX} === Generating EVM Verifier ===");
    let path_verifier_sol = verifier_output_dir.join("verifier.sol");
    let path_verifier_bin = verifier_output_dir.join("verifier.bin");
    let path_root_agg_pk = verifier_output_dir.join("root_verifier_vk");

    // Skip regeneration in auto mode when artifacts already exist.
    if !force_overwrite && path_verifier_sol.exists() && path_verifier_bin.exists() {
        println!(
            "{LOG_PREFIX} EVM verifier files already exist, skipping (use --mode force to overwrite)"
        );
        return Ok(());
    }

    if let Some(parent) = path_verifier_bin.parent() {
        fs::create_dir_all(parent)?;
    }

    let app_params = app_params_with_100_bits_security(MAX_APP_LOG_STACKED_HEIGHT);
    let agg_params = default_agg_params();

    if !recompute_mode {
        println!(
            "{LOG_PREFIX} WARNING: RECOMPUTE_MODE is not set. The EVM verifier will be downloaded \
             from openvm-solidity-sdk, which currently does not publish a v2-compatible verifier. \
             verifier.bin will be EMPTY and EVM proof verification will fail. \
             Run with RECOMPUTE_MODE=yes to generate the verifier locally."
        );
    }

    let sdk = if recompute_mode {
        // 1. Build a batch SDK to serve as the child circuit for bundle's deferral prover.
        let batch_config_path = release_output_dir.join("batch").join(FD_APP_CONFIG);
        let batch_app_config: AppConfig<SdkVmConfig> = if batch_config_path.exists() {
            toml::from_str(&fs::read_to_string(&batch_config_path)?)?
        } else {
            AppConfig::riscv32(app_params.clone())
        };
        let batch_sdk = Sdk::builder()
            .app_config(batch_app_config)
            .agg_params(agg_params.clone())
            .build()?;

        // 2. Load the bundle config so the verifier matches the bundle circuit's
        //    aggregation-tree shape and deferral settings.
        let bundle_config_path = release_output_dir.join("bundle").join(FD_APP_CONFIG);
        let bundle_app_config: AppConfig<SdkVmConfig> = if bundle_config_path.exists() {
            toml::from_str(&fs::read_to_string(&bundle_config_path)?)?
        } else {
            AppConfig::riscv32(app_params.clone())
        };

        // The bundle's deferral circuit verifies batch proofs; its memory layout must
        // match the bundle VM config, not the batch config.
        let deferral_prover = make_deferral_prover(&batch_sdk,
            &bundle_app_config,
            &agg_params,
        );

        Sdk::builder()
            .app_config(bundle_app_config)
            .agg_params(agg_params)
            .agg_tree_config(DEFAULT_AGG_TREE_CONFIG)
            .multi_deferral_circuit_prover(deferral_prover)
            .build()?
    } else {
        Sdk::riscv32(app_params, agg_params)
    };

    let verifier = if recompute_mode {
        sdk.generate_halo2_verifier_solidity()?
    } else {
        verifier::download_evm_verifier()?
    };

    // Write the root aggregation VK from the same SDK used to generate the verifier.
    // This must match the bundle circuit's deferral config and aggregation tree shape.
    if force_overwrite || !path_root_agg_pk.exists() {
        write_object_to_file(
            &path_root_agg_pk,
            sdk.agg_vk().clone(),
        )
        .expect("failed to write root_verifier_vk");
    }

    // In v2, the EVM verifier is split into multiple Solidity files.
    // We save the full set so external tools (Foundry, etc.) can recompile.
    if !verifier.halo2_verifier_code.is_empty() {
        let path_halo2 = verifier_output_dir.join("Halo2Verifier.sol");
        fs::write(&path_halo2, &verifier.halo2_verifier_code)?;
        println!("{LOG_PREFIX} Halo2Verifier.sol written to {path_halo2:?}");
    }
    if !verifier.openvm_verifier_interface.is_empty() {
        let path_interfaces = verifier_output_dir.join("interfaces");
        fs::create_dir_all(&path_interfaces)?;
        let path_interface = path_interfaces.join("IOpenVmHalo2Verifier.sol");
        fs::write(&path_interface, &verifier.openvm_verifier_interface)?;
        println!("{LOG_PREFIX} IOpenVmHalo2Verifier.sol written to {path_interface:?}");
    }

    // Backwards-compatible names used by the Rust verifier.
    fs::write(&path_verifier_sol, &verifier.openvm_verifier_code)?;
    println!("{LOG_PREFIX} verifier_sol (OpenVmHalo2Verifier) written to {path_verifier_sol:?}");

    fs::write(&path_verifier_bin, &verifier.artifact.bytecode)?;
    println!("{LOG_PREFIX} verifier_bin written to {path_verifier_bin:?}");

    Ok(())
}

fn generate_openvm_assets(
    workspace_dir: &PathBuf,
    release_output_dir: &PathBuf,
    force_overwrite: bool,
) -> Result<()> {
    // to use the 'foundry.toml'
    env::set_current_dir(workspace_dir)?;

    generate_root_verifier(workspace_dir, force_overwrite)?;
    let recompute_mode = env::var("RECOMPUTE_MODE").is_ok_and(|value| value == "yes");
    generate_evm_verifier(
        workspace_dir,
        release_output_dir,
        &release_output_dir.join("verifier"),
        recompute_mode,
        force_overwrite,
    )?;
    Ok(())
}

pub fn main() -> Result<()> {
    let cli = Cli::parse();

    println!("{LOG_PREFIX} Generation mode: {:?}", cli.mode);
    println!("{LOG_PREFIX} Will generate both app and openvm assets");

    // Set current directory to the crate's root
    let manifest_dir = env::var("CARGO_MANIFEST_DIR")?;
    env::set_current_dir(&manifest_dir)?;
    println!("{LOG_PREFIX} Running in directory: {}", manifest_dir);

    // Load .env file if present
    dotenv().ok();

    // Determine workspace root
    let metadata = cargo_metadata::MetadataCommand::new().exec()?;
    let workspace_dir = metadata.workspace_root.into_std_path_buf();
    println!("{LOG_PREFIX} Workspace root: {}", workspace_dir.display());

    let release_output_dir: PathBuf = workspace_dir.join("releases").join(&cli.output);
    fs::create_dir_all(&release_output_dir)?;
    println!(
        "{LOG_PREFIX} Release output directory: {}",
        release_output_dir.display()
    );

    println!("{LOG_PREFIX} Generating openvm assets");
    let force_overwrite = matches!(cli.mode, OutputMode::Force);
    println!("{LOG_PREFIX} Generating app assets (always overwrite)");
    generate_app_assets(&workspace_dir, &release_output_dir)?;

    println!("{LOG_PREFIX} Generating openvm assets");
    generate_openvm_assets(&workspace_dir, &release_output_dir, force_overwrite)?;

    println!("{LOG_PREFIX} Build process completed successfully.");
    Ok(())
}
