#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1014022064, 465731548, 1523753209, 176670569, 1674631214, 1423438392, 1005554882, 394958993];
