#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1303559324, 1894411562, 683816819, 1138777461, 5450950, 1920371602, 1646997810, 1849856934];
