#!/bin/bash
set -euxo pipefail

# Alas, the openvm CLI does not offer `clippy` as a subcommand,
# so we have to use `cargo` directly.  The options are copy-and-pasted from
# `openvm`'s `build` command.
clippycmd="cargo +nightly-2024-10-30 clippy \
  --target riscv32im-risc0-zkvm-elf \
  -Z build-std=alloc,core,proc_macro,panic_abort,std \
  -Z build-std-features=compiler-builtins-mem \
  --all-targets \
  --all-features \
  -- -D warnings"

cd crates/circuits/chunk-circuit; eval "$clippycmd"; cd ./../../..
cd crates/circuits/chunk-circuit; eval "$clippycmd"; cd ./../../..
cd crates/circuits/chunk-circuit; eval "$clippycmd"; cd ./../../..
