use openvm_sdk::types::AppExecutionCommit;
use openvm_stark_sdk::openvm_stark_backend::keygen::types::MultiStarkVerifyingKey;
use openvm_stark_sdk::openvm_stark_backend::{codec::Decode, p3_field::PrimeField32, proof::Proof};
use openvm_sdk::SC;
use openvm_sdk::Sdk;
use openvm_continuations::CommitBytes;
use scroll_zkvm_types::proof::OpenVmEvmProof;
use scroll_zkvm_types::{proof::StarkProof, utils::serialize_vk};
use std::path::Path;

pub use scroll_zkvm_types::zkvm::AGG_STARK_PROVING_KEY;

/// Verifier capable of checking both STARK and EVM (Halo2 SNARK) proofs.
///
/// Loads the aggregation verifying key (`loaded_mvk`) and EVM verifier bytecode
/// (`evm_verifier`) from the release directory at setup time.
pub struct UniversalVerifier {
    /// EVM verifier bytecode deployed to simulate on-chain verification.
    pub evm_verifier: Vec<u8>,
    /// Aggregation STARK verifying key used to verify STARK proofs.
    pub loaded_mvk: MultiStarkVerifyingKey<SC>,
}

impl UniversalVerifier {
    /// Verify a STARK proof against the given aggregation verifying key.
    ///
    /// # Commitment check
    /// The `vk` bytes encode the expected program commitment (`exe` + `vm`).
    /// We compare the `exe` commitment against the proof baseline to ensure the
    /// proof was generated by the expected guest program.
    ///
    /// # Deferral support
    /// OpenVM v2+ proofs may contain `deferral_merkle_proofs`. If present they
    /// are decoded and passed to the verifier.
    pub fn verify_stark_proof_with_vk(
        agg_mvk: &MultiStarkVerifyingKey<SC>,
        stark_proof: &StarkProof,
        vk: &[u8],
    ) -> eyre::Result<()> {
        let prog_commit = serialize_vk::deserialize(vk);

        use openvm_verify_stark_host::{vk::VerificationBaseline, VmStarkProof};
        let baseline: VerificationBaseline = if stark_proof.baseline.is_empty() {
            eyre::bail!("stark proof missing verification baseline (v2+ required)");
        } else {
            serde_json::from_slice(&stark_proof.baseline)?
        };

        let deferral_merkle_proofs = if stark_proof.deferral_merkle_proofs.is_empty() {
            None
        } else {
            Some(openvm_verify_stark_host::deferral::DeferralMerkleProofs::decode(
                &mut std::io::Cursor::new(&stark_proof.deferral_merkle_proofs),
            )?)
        };
        let vm_stark_proof = VmStarkProof {
            inner: Proof::<SC>::decode_from_bytes(&stark_proof.proof)?,
            user_pvs_proof: {
                use openvm_circuit::system::memory::merkle::public_values::UserPublicValuesProof;
                UserPublicValuesProof::decode::<SC, _>(&mut std::io::Cursor::new(&stark_proof.user_pvs_proof))?
            },
            deferral_merkle_proofs,
        };
        let _expected_app_commit = AppExecutionCommit {
            app_exe_commit: CommitBytes::from(prog_commit.exe),
            app_vm_commit: CommitBytes::from(prog_commit.vm),
        };
        // Compare the expected program commitment (from vk) against the proof baseline.
        // The baseline is derived from the STARK proof's public inputs / commitments.
        let baseline_exe_commit: [u32; 8] = baseline.app_exe_commit.map(|f| f.as_canonical_u32());
        if prog_commit.exe != baseline_exe_commit {
            eyre::bail!("stark: mismatch EXE commitment");
        }

        Sdk::verify_proof(agg_mvk.clone(), baseline, &vm_stark_proof)?;

        Ok(())
    }

    /// Load verifier assets from a release directory.
    ///
    /// Expects:
    /// - `{path_verifier}/verifier.bin` — EVM verifier bytecode
    /// - `{path_verifier}/root_verifier_vk` — serialized aggregation VK
    ///
    /// Falls back to computing the VK on-the-fly if the file is missing (slow).
    pub fn setup<P: AsRef<Path>>(path_verifier: P) -> eyre::Result<Self> {
        let path_verifier_code = path_verifier.as_ref().join("verifier.bin");
        let path_agg_vk = path_verifier.as_ref().join("root_verifier_vk");
        let evm_verifier = std::fs::read(path_verifier_code)?;

        let loaded_mvk = openvm_sdk::fs::read_object_from_file(path_agg_vk).unwrap_or_else(
            |_| {
                tracing::warn!("root_verifier_vk not found on disk, computing on-the-fly (slow)...");
                AGG_STARK_PROVING_KEY.internal_recursive.get_vk().clone()
            }
        );

        Ok(Self {
            evm_verifier,
            loaded_mvk,
        })
    }

    pub fn verify_stark_proof(&self, stark_proof: &StarkProof, vk: &[u8]) -> eyre::Result<()> {
        Self::verify_stark_proof_with_vk(&self.loaded_mvk, stark_proof, vk)
    }

    /// Verify an EVM (Halo2 SNARK) proof.
    ///
    /// # Commitment check
    /// Before running the EVM bytecode, we check that the proof's app commitments
    /// (`app_exe_commit`, `app_vm_commit`) match the expected values encoded in `vk`.
    /// This prevents verifying a proof generated for a different circuit version.
    pub fn verify_evm_proof(&self, evm_proof: &OpenVmEvmProof, vk: &[u8]) -> eyre::Result<()> {
        let prog_commit = serialize_vk::deserialize(vk);

        let evm_exe_commit: [openvm_sdk::F; 8] = evm_proof.app_commit.app_exe_commit.into();
        let evm_exe_commit_u32: [u32; 8] = evm_exe_commit.map(|f| f.as_canonical_u32());

        let evm_vm_commit: [openvm_sdk::F; 8] = evm_proof.app_commit.app_vm_commit.into();
        let evm_vm_commit_u32: [u32; 8] = evm_vm_commit.map(|f| f.as_canonical_u32());

        if evm_exe_commit_u32 != prog_commit.exe {
            eyre::bail!("evm: mismatch EXE commitment");
        }
        if evm_vm_commit_u32 != prog_commit.vm {
            eyre::bail!("evm: mismatch VM commitment");
        }

        crate::evm::verify_evm_proof(&self.evm_verifier, evm_proof)
            .map_err(|e| eyre::eyre!("evm execution failed: {e}"))?;

        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use crate::test::WrappedProof;
    use scroll_zkvm_types::proof::ProofEnum;
    use std::path::Path;

    use super::*;

    const PATH_TESTDATA: &str = "./testdata";

    impl UniversalVerifier {
        /// test method to be compatible with euclid wrapped proofs
        pub fn verify_wrapped_proof(&self, proof: &WrappedProof) -> eyre::Result<()> {
            match &proof.proof {
                ProofEnum::Evm(p) => self.verify_evm_proof(&p.clone().into(), &proof.vk),
                ProofEnum::Stark(p) => self.verify_stark_proof(p, &proof.vk),
            }
        }
    }

    #[ignore = "need euclid released assets"]
    #[test]
    fn verify_chunk_proof() -> eyre::Result<()> {
        let chunk_proof = WrappedProof::from_json(
            Path::new(PATH_TESTDATA)
                .join("proofs")
                .join("chunk-proof-feynman.json"),
        )?;
        let verifier = UniversalVerifier::setup(Path::new(PATH_TESTDATA))?;

        let stark_proof = chunk_proof.proof.as_stark_proof().unwrap();
        verifier.verify_stark_proof(stark_proof, &chunk_proof.vk)?;

        Ok(())
    }

    #[ignore = "need euclid released assets"]
    #[test]
    fn verify_batch_proof() -> eyre::Result<()> {
        let batch_proof = WrappedProof::from_json(
            Path::new(PATH_TESTDATA)
                .join("proofs")
                .join("batch-proof-feynman.json"),
        )?;
        let verifier = UniversalVerifier::setup(Path::new(PATH_TESTDATA))?;

        let stark_proof = batch_proof.proof.as_stark_proof().unwrap();
        verifier.verify_stark_proof(stark_proof, &batch_proof.vk)?;

        Ok(())
    }

    #[ignore = "need euclid released assets"]
    #[test]
    fn verify_bundle_proof() -> eyre::Result<()> {
        let evm_proof = WrappedProof::from_json(
            Path::new(PATH_TESTDATA)
                .join("proofs")
                .join("bundle-proof-phase2.json"),
        )?;

        let verifier = UniversalVerifier::setup(Path::new(PATH_TESTDATA))?;

        verifier.verify_evm_proof(
            &evm_proof.proof.into_evm_proof().unwrap().into(),
            &evm_proof.vk,
        )?;

        Ok(())
    }
}
