// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import {Test, console} from "forge-std/Test.sol";
import {SP1Verifier} from "../lib/sp1-contracts/contracts/src/v6.1.0/SP1VerifierPlonk.sol";

/// @notice End-to-end on-chain verification test for the SP1 bundle Plonk proof.
/// @dev This test expects the bundle proving artifacts to already exist at
///      `../releases/dev/sp1/prover-test/` (generated by `prove-sp1 --circuit bundle`).
contract SP1BundleVerifierTest is Test {
    function testVerifyBundleProof() public {
        SP1Verifier verifier = new SP1Verifier();

        bytes32 programVKey =
            vm.parseBytes32(vm.readFile("../releases/dev/sp1/prover-test/bundle_vk_hash.txt"));
        bytes memory publicValues =
            vm.readFileBinary("../releases/dev/sp1/prover-test/bundle_public_values.bin");
        bytes memory proofBytes =
            vm.readFileBinary("../releases/dev/sp1/prover-test/bundle_proof_bytes.bin");

        uint256 gasBefore = gasleft();
        verifier.verifyProof(programVKey, publicValues, proofBytes);
        uint256 gasAfter = gasleft();
        console.log("verifyProof gas used:", gasBefore - gasAfter);
    }
}
