[package]
name = "scroll-zkvm-types-base"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
alloy-primitives = { workspace = true, default-features = false, features = ["std", "map-hashbrown", "map-fxhash", "rkyv"] }
alloy-serde.workspace = true
rkyv.workspace = true
sbv-primitives = { workspace = true, features = ["scroll-consensus-types", "scroll-reth-types"] }
serde.workspace = true
itertools.workspace = true
tiny-keccak = { workspace = true }
sha3 = "0.10.8"
sha2 = "0.10.8"

[features]
default = []
