[package]
name = "scroll-zkvm-types-base"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
alloy-primitives = { workspace = true }
alloy-serde.workspace = true
rkyv.workspace = true
serde.workspace = true
sha3 = "0.10.8"
sha2 = "0.10.8"

[features]
default = []
