#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [123293429, 661502243, 1332640210, 533174887, 1591197618, 1101567153, 1899493398, 49094928];
