[package]
name = "scroll-zkvm-chunk-circuit"
edition.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
openvm = { git = "https://github.com/openvm-org/openvm.git",  rev = "fc90b5d", features = ["std"] }
openvm-algebra-complex-macros = { git = "https://github.com/openvm-org/openvm.git",  rev = "fc90b5d" } 
openvm-algebra-guest = { git = "https://github.com/openvm-org/openvm.git",  rev = "fc90b5d" }
openvm-bigint-guest = { git = "https://github.com/openvm-org/openvm.git",  rev = "fc90b5d" }
openvm-ecc-guest = { git = "https://github.com/openvm-org/openvm.git",  rev = "fc90b5d", features = ["k256"] }
openvm-keccak256-guest= { git = "https://github.com/openvm-org/openvm.git",  rev = "fc90b5d" }
openvm-pairing-guest = { git = "https://github.com/openvm-org/openvm.git",  rev = "fc90b5d", features = ["bn254"] }
openvm-rv32im-guest= {  git = "https://github.com/openvm-org/openvm.git",  rev = "fc90b5d" }
rkyv.workspace = true
sbv.workspace = true

[features]
default = ["scroll"]
scroll = ["sbv/scroll"]
