#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [636098662, 1159240103, 1476249019, 1206808598, 446929719, 1171493582, 43492796, 756143264];
