#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [896258503, 1264789376, 1894783211, 1331236681, 1464277710, 1435311184, 1585165466, 1219971142];
