#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1916403529, 248532006, 62641213, 1966672652, 202623446, 8976636, 1202785404, 1689391190];
