#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1141687350, 1440693223, 1179270389, 1952797670, 1817898789, 857577465, 1104882240, 105793721];
