#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [958792225, 1935761634, 1917270778, 1345650433, 893401029, 881801606, 253898493, 1069576020];
