#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [22562954, 482987742, 964163105, 163124564, 785704068, 1262367352, 1022134348, 339887702];
