#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [772167398, 274296420, 122391362, 18861170, 1678047186, 1143048180, 1123167759, 1472433101];
