#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1278216950, 615031465, 469053169, 1209049901, 1697168163, 663367631, 113121555, 917336839];
