#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [388965117, 634149964, 1301101304, 136264277, 316201108, 365084570, 1135330922, 195059385];
