#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1209101837, 99643033, 996198416, 1107956009, 1219145045, 927684997, 1902587021, 1745407319];
