#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [310007309, 1583937256, 1239050703, 1961913597, 371788238, 374728480, 340481313, 1103367244];
