#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1327831041, 1333938578, 1465924054, 265598051, 217303637, 1482374516, 658833638, 1874751238];
