[package]
name = "scroll-zkvm-circuit-input-types"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
alloy-primitives = { workspace = true, default-features = false, features = ["std", "map-hashbrown", "map-fxhash", "rkyv"] }
alloy-serde.workspace = true
rkyv.workspace = true
serde.workspace = true
tiny-keccak.workspace = true

openvm = { git = "https://github.com/openvm-org/openvm.git", rev = "d45b226", features = ["std"] }
openvm-rv32im-guest= {  git = "https://github.com/openvm-org/openvm.git", rev = "d45b226" }

[features]
scroll = []
