[package]
name = "scroll-zkvm-tools-flatten-root-proof"
version.workspace = true
edition.workspace = true

[dependencies]
scroll-zkvm-circuit-input-types.workspace = true
scroll-zkvm-prover.workspace = true

openvm.workspace = true
openvm-native-recursion.workspace = true
openvm-sdk.workspace = true
openvm-stark-sdk.workspace = true

derivative.workspace = true
serde.workspace = true
bitcode.workspace = true
halo2curves-axiom.workspace = true
toml.workspace = true
