[patch.crates-io]
k256 = { git = "https://github.com/openvm-org/openvm.git", branch = "feat/new-execution" }
p256 = { git = "https://github.com/openvm-org/openvm.git", branch = "feat/new-execution" }
