[package]
name = "chunk-guest"
edition = "2021"

[workspace]

[dependencies]
risc0-zkvm = { version = "^2.3.1", default-features = false, features = ["std", "unstable"] }
rkyv = "0.8"
scroll-zkvm-types-chunk = { path = "../../../types/chunk" }

[patch.crates-io]
revm = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-bytecode = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-context = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-context-interface = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-database = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-database-interface = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-handler = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-inspector = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-interpreter = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-precompile = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-primitives = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }
revm-state = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v78" }

ruint = { git = "https://github.com/scroll-tech/uint.git", branch = "v1.15.0" }
alloy-primitives = { git = "https://github.com/scroll-tech/alloy-core", branch = "v1.2.0" }

blst = { git = "https://github.com/risc0/blst", tag = "blst/v0.3.14-risczero.1" }
crypto-bigint = { git = "https://github.com/risc0/RustCrypto-crypto-bigint", tag = "v0.5.5-risczero.0" }
c-kzg = { git = "https://github.com/risc0/c-kzg-4844", tag = "c-kzg/v2.1.1-risczero.0" }
k256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "k256/v0.13.4-risczero.1" }
p256 = { git = "https://github.com/risc0/RustCrypto-elliptic-curves", tag = "p256/v0.13.2-risczero.1" }
sha2-10-8 = { package = "sha2", git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.10.8-risczero.0" }
sha2-9-9 = { package = "sha2", git = "https://github.com/risc0/RustCrypto-hashes", tag = "sha2-v0.9.9-risczero.0" }
tiny-keccak = { git = "https://github.com/risc0/tiny-keccak", tag = "tiny-keccak/v2.0.2-risczero.0" }

#[patch.'https://github.com/scroll-tech/reth']
#reth-chainspec = { path = "../../../../../reth/crates/chainspec" }
#reth-evm = { path = "../../../../../reth/crates/evm/evm" }
#reth-evm-ethereum = { path = "../../../../../reth/crates/ethereum/evm" }
#reth-ethereum-forks = { path = "../../../../../reth/crates/ethereum/hardforks" }
#reth-execution-types = { path = "../../../../../reth/crates/evm/execution-types" }
#reth-primitives = { path = "../../../../../reth/crates/primitives" }
#reth-primitives-traits = { path = "../../../../../reth/crates/primitives-traits" }
#reth-storage-errors = { path = "../../../../../reth/crates/storage/errors" }
#reth-trie = { path = "../../../../../reth/crates/trie/trie" }
#reth-trie-sparse = { path = "../../../../../reth/crates/trie/sparse" }
#
#reth-scroll-chainspec = { path = "../../../../../reth/crates/scroll/chainspec" }
#reth-scroll-evm = { path = "../../../../../reth/crates/scroll/evm" }
#reth-scroll-forks = { path = "../../../../../reth/crates/scroll/hardforks" }
#reth-scroll-primitives = { path = "../../../../../reth/crates/scroll/primitives" }
#
#scroll-alloy-evm = { path = "../../../../../reth/crates/scroll/alloy/evm" }
#scroll-alloy-consensus = { path = "../../../../../reth/crates/scroll/alloy/consensus" }
