[package]
name = "scroll-zkvm-types-chunk"
authors.workspace = true
edition.workspace = true
homepage.workspace = true
readme.workspace = true
repository.workspace = true
version.workspace = true

[dependencies]
alloy-primitives = { workspace = true, features = ["native-keccak"] }
alloy-sol-types.workspace = true
ecies.workspace = true
itertools.workspace = true
#revm-precompile = { git = "https://github.com/scroll-tech/revm", branch = "feat/reth-v74", default-features=false, features = ["kzg-rs", "libsecp256k1"] }
rkyv.workspace = true
sbv-helpers.workspace = true
sbv-core = { workspace = true }
sbv-primitives = { workspace = true, features = ["hardforks", "scroll-hardforks", "scroll-revm-types"] }
serde.workspace = true
thiserror.workspace = true

types-base = { path = "../base", package = "scroll-zkvm-types-base"}

[features]
default = []
host = ["scroll-compress-ratio"]
scroll-compress-ratio = ["sbv-primitives/scroll-compress-ratio"]
openvm = ["sbv-core/scroll-openvm"]
