#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [258286775, 1730996537, 1506947376, 1543524989, 653280630, 1028288165, 259337800, 1416761391];
