#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1564750536, 1199068721, 1357124636, 509005417, 850566565, 719694908, 1451454140, 1537636711];
