#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [830278672, 9058437, 1623618274, 791292874, 1035401947, 1412813097, 214194085, 1529698223];
