#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1986621377, 858531750, 1460740544, 1489416258, 402142684, 1028207948, 2010771520, 956067622];
