#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [569618779, 539923570, 1778203254, 1822379905, 832957374, 126873631, 404509153, 1002093313];
