#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1473077767, 915340244, 1015753118, 931874796, 1629597349, 1264003766, 1595028109, 54844257];
