#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1881598004, 970250555, 1933976758, 277699807, 1238449309, 1025509899, 1136847759, 777751013];
