#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [938731734, 152130481, 1529869971, 1510773152, 1107646849, 1319186509, 1823457883, 138842638];
