#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [11378421, 1794249118, 1140536335, 1670161200, 13985221, 1965565359, 821783138, 2009097060];
