#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [961556313, 1731047867, 72985453, 1903143291, 1547370790, 808064965, 1660332517, 1005769700];
