#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [767961627, 1863676756, 1816887039, 1021890519, 303786683, 1279626877, 1177909236, 742426219];
