#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1730948446, 592379163, 30730427, 1108807042, 587065798, 698750563, 1595566218, 1990233667];
