#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1348218286, 1377485599, 709357348, 698981115, 437947804, 409122197, 1670351262, 918232653];
