[package]
name = "generate-verifier-asm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

serde = { workspace = true}
serde_json = { workspace = true}
serde_with = { workspace = true}
halo2curves-axiom = { workspace = true}
p3-field = { workspace = true}
bitcode = { workspace = true}
openvm-stark-sdk = { workspace = true}
openvm-sdk = { workspace = true}
openvm-instructions = { workspace = true}
openvm-native-compiler = { workspace = true}
openvm-native-recursion = { workspace = true}
openvm-rv32im-transpiler = { workspace = true}
snark-verifier-sdk = { workspace = true}
