#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1427402185, 1459064843, 317464538, 1274190978, 466682983, 1321271389, 1187009604, 1464042898];
