#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1197989042, 1009784096, 452031800, 1163893158, 333844333, 60630125, 972528405, 694907184];
