#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [201161368, 1899692875, 57302023, 1414522389, 1405245774, 311196883, 1031375563, 825047078];
