#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1792226047, 611100767, 1146270814, 1810005845, 1491201797, 1214999763, 783504632, 1498168266];
