#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT OVERWRITE!

pub const COMMIT: [u32; 8] = [12988142, 1056974730, 1268625384, 1258697214, 1638476404, 617136570, 486525037, 565660780];
