#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [805082440, 895615512, 1350654034, 708051794, 1929086621, 1197019451, 1765506679, 1801810773];
