#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [1790507673, 940757639, 1596528283, 787297239, 1810335619, 1645701266, 1623655916, 833943635];
