#![cfg_attr(rustfmt, rustfmt_skip)]
//! Generated by crates/build-guest. DO NOT EDIT!

pub const COMMIT: [u32; 8] = [154909400, 568977126, 398881389, 857512330, 1452867858, 211440187, 843000158, 1773648841];
