name: Build Guest

on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - master
      - release/*
    paths:
      - crates/circuits/types/**/*
      - crates/circuits/chunk-circuit/**/*
      - crates/circuits/batch-circuit/**/*
      - crates/circuits/bundle-circuit/**/*
      - crates/build-guest/**/*
      - Cargo.lock
  push:
    branches:
      - master
      - release/*
    paths:
      - crates/circuits/types/**/*
      - crates/circuits/chunk-circuit/**/*
      - crates/circuits/batch-circuit/**/*
      - crates/circuits/bundle-circuit/**/*
      - crates/build-guest/**/*
      - Cargo.lock

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-guest:
    name: Docker containerized build of guest programs
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: chunk commitments (prover)
        id: commitments-chunk-prover
        run: |
          {
            echo 'commitments<<EOF'
            cat crates/prover/src/commitments/chunk.rs
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: batch commitments (prover)
        id: commitments-batch-prover
        run: |
          {
            echo 'commitments<<EOF'
            cat crates/prover/src/commitments/batch.rs
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: bundle commitments (prover)
        id: commitments-bundle-prover
        run: |
          {
            echo 'commitments<<EOF'
            cat crates/prover/src/commitments/bundle.rs
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: chunk commitments (verifier)
        id: commitments-chunk-verifier
        run: |
          {
            echo 'commitments<<EOF'
            cat crates/verifier/src/commitments/chunk.rs
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: batch commitments (verifier)
        id: commitments-batch-verifier
        run: |
          {
            echo 'commitments<<EOF'
            cat crates/verifier/src/commitments/batch.rs
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: bundle commitments (verifier)
        id: commitments-bundle-verifier
        run: |
          {
            echo 'commitments<<EOF'
            cat crates/verifier/src/commitments/bundle.rs
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: chunk commitments (circuits)
        id: commitments-chunk-circuits
        run: |
          {
            echo 'commitments<<EOF'
            cat crates/circuits/batch-circuit/src/child_commitments.rs
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: batch commitments (circuits)
        id: commitments-batch-circuits
        run: |
          {
            echo 'commitments<<EOF'
            cat crates/circuits/bundle-circuit/src/child_commitments.rs
            echo EOF
          } >> $GITHUB_OUTPUT

      - name: Sanity check for chunk-commitments (prover vs verifier)
        uses: nick-fields/assert-action@v1
        with:
          expected: ${{ steps.commitments-chunk-prover.outputs.commitments }}
          actual: ${{ steps.commitments-chunk-verifier.outputs.commitments }}

      - name: Sanity check for chunk-commitments (prover vs circuits)
        uses: nick-fields/assert-action@v1
        with:
          expected: ${{ steps.commitments-chunk-prover.outputs.commitments }}
          actual: ${{ steps.commitments-chunk-circuits.outputs.commitments }}

      - name: Sanity check for batch-commitments (prover vs verifier)
        uses: nick-fields/assert-action@v1
        with:
          expected: ${{ steps.commitments-batch-prover.outputs.commitments }}
          actual: ${{ steps.commitments-batch-verifier.outputs.commitments }}

      - name: Sanity check for batch-commitments (prover vs circuits)
        uses: nick-fields/assert-action@v1
        with:
          expected: ${{ steps.commitments-batch-prover.outputs.commitments }}
          actual: ${{ steps.commitments-batch-circuits.outputs.commitments }}

      - name: Sanity check for bundle-commitments (prover vs verifier)
        uses: nick-fields/assert-action@v1
        with:
          expected: ${{ steps.commitments-bundle-prover.outputs.commitments }}
          actual: ${{ steps.commitments-bundle-verifier.outputs.commitments }}

      - name: Build guest and check diff
        run: |
          make build-guest
          git diff

      - name: Configure Git
        run: |
          git config --local user.name "GitHub Actions Bot"
          git config --local user.email "actions@github.com"

      - name: Commit changes (commitments)
        id: commit-commitments
        run: |
          git add crates/prover/src/commitments/chunk.rs
          git add crates/prover/src/commitments/batch.rs
          git add crates/prover/src/commitments/bundle.rs
          git add crates/verifier/src/commitments/chunk.rs
          git add crates/verifier/src/commitments/batch.rs
          git add crates/verifier/src/commitments/bundle.rs
          git add crates/circuits/batch-circuit/src/child_commitments.rs
          git add crates/circuits/bundle-circuit/src/child_commitments.rs
          git commit -m "[Automated] chore: update commitments" || echo "No changes to commit"
          echo "COMMIT_REF=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT

      - name: Push changes (commitments)
        run: |
          git push origin ${{ github.head_ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Upload app exe to s3
        run: |
          aws s3 cp crates/circuits/chunk-circuit/openvm/app.vmexe s3://circuit-release/scroll-zkvm/${{ steps.commit-commitments.outputs.COMMIT_REF }}/chunk/app.vmexe
          aws s3 cp crates/circuits/batch-circuit/openvm/app.vmexe s3://circuit-release/scroll-zkvm/${{ steps.commit-commitments.outputs.COMMIT_REF }}/batch/app.vmexe
          aws s3 cp crates/circuits/bundle-circuit/openvm/app.vmexe s3://circuit-release/scroll-zkvm/${{ steps.commit-commitments.outputs.COMMIT_REF }}/bundle/app.vmexe
      
      - name: Upload artifact (chunk app.vmexe)
        uses: actions/upload-artifact@v4
        with:
          name: chunk-app-vmexe
          path: ./crates/circuits/chunk-circuit/openvm/app.vmexe

      - name: Upload artifact (batch app.vmexe)
        uses: actions/upload-artifact@v4
        with:
          name: batch-app-vmexe
          path: ./crates/circuits/batch-circuit/openvm/app.vmexe

      - name: Upload artifact (bundle app.vmexe)
        uses: actions/upload-artifact@v4
        with:
          name: bundle-app-vmexe
          path: ./crates/circuits/bundle-circuit/openvm/app.vmexe

      - name: Upload artifact (root verifier)
        uses: actions/upload-artifact@v4
        with:
          name: root-verifier-asm
          path: ./crates/build-guest/root_verifier.asm
