name: Build Guest

on:
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]
    branches:
      - master
      - release/*
    paths:
      - crates/circuits/types/**/*
      - crates/circuits/chunk-circuit/**/*
      - crates/circuits/batch-circuit/**/*
      - crates/circuits/bundle-circuit/**/*
      - crates/build-guest/**/*
  push:
    branches:
      - master
      - release/*
    paths:
      - crates/circuits/types/**/*
      - crates/circuits/chunk-circuit/**/*
      - crates/circuits/batch-circuit/**/*
      - crates/circuits/bundle-circuit/**/*
      - crates/build-guest/**/*
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  docker-build-guest:
    name: Docker containerized build of guest programs
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Build guest and check diff
        run: |
          make build-guest
          git diff
          git diff --quiet && echo "no diff" || (echo "diff"; exit 1)

      - name: Upload artifact (chunk app.vmexe)
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 #v4.6.2
        with:
          name: chunk-app-vmexe
          path: ./crates/circuits/chunk-circuit/openvm/app.vmexe
