name: Build ZKVM-Prover Guest

on:
  push:
    tags:
      - **

jobs:
  build-guest:
    runs-on: ubuntu-latest
    env:
      SCROLL_ZKVM_VERSION: ${{ github.ref_name }}
      DIR_OUTPUT: releases/dev
      AWS_REGION: us-west-2

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install xxd
        run: sudo apt-get update && sudo apt-get install -y vim-common

      - name: Install Rust nightly toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.86
          target: x86_64-unknown-linux-gnu
          components: rust-src
          override: true

      - name: Cache cargo registry and build
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Build guest binary
        run: make build-guest 
        
      - name: Prepare release
        run: |
          # checksum for assets
          find $DIR_OUTPUT  -type f ! -name sha256sums.txt  -exec sha256sum {} \; > $DIR_OUTPUT/sha256sums.txt

      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@v1
        with:
          version: 2
          verbose: false
          arch: amd64

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Upload releases to S3
        run: |
          aws s3 cp $DIR_OUTPUT s3://circuit-release/scroll-zkvm/${{ github.ref_name }} --recursive
